export {default as sliderPhoto} from "./sliderPhoto"
export {default as sliderVideo} from "./sliderVideo"
export {default as title} from "./title"
export {default as video} from "./video"
export {default as catalog} from "./catalog"