export {default as SliderPhoto} from "./sliderPhoto"
export {default as SliderVideo} from "./sliderVideo"
export {default as Title} from "./title"
export {default as Video} from "./video"
export {default as Catalog} from "./catalog"