export {default as Landing} from "./landing"
export {default as Wedding} from "./weddings"
export {default as Abayas} from "./abayas"
export {default as Beauty} from "./beauty"
export {default as Accessories} from "./accessories"